[tool.black]
line-length = 88  # Default line length that works well with Flake8
target-version = ['py311']  # Set to the version of Python you are using
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88  # Ensure the line length matches Black and Flake8
multi_line_output = 3  # Ensure similar line breaks for imports as Black
include_trailing_comma = true  # Matches Black's default style
