name: CI Pipeline

on:
    pull_request:
        branches:
            - '**'
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pipenv
            pipenv install 
            pipenv install --dev

        - name: Check code quality with flake8
          run: |
            pipenv run flake8 .

        - name: Test with pytest
          run: |
            pipenv run pytest