name: Pipeline

on:
    pull_request:
        branches:
            - '**'
    push:
        branches:
            - '**'

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.11
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pipenv'

        - name: Install pipenv
          run: |
            curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

        - name: Install dependencies
          run: |
            pipenv install 
            pipenv install --dev

        - name: Check code quality with flake8
          run: |
            pipenv run flake8 .

        - name: Unit tests with pytest
          run: |
            pipenv run pytest tests/unit

        - name: Integration tests with pytest
          run: |
            pipenv run pytest tests/integration